version: "3"

services:
    plex-utills:
        image: jkirkcaldy/plex-utills
        container_name: plex-utills
        restart: unless-stopped
        volumes: 
            - <your Plex media directory>:/films
            - <your config location>:/config
            - <your log location>:/logs
        environment: 
            - TZ=Europe/London
        ports:
            - 80:80
        cap_add:
          - SYS_ADMIN
          - DAC_READ_SEARCH